services:
  my-app:
    image: idror/cicd-jenkins-project
    ports:
      - "5053:5052"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=admin
      - DB_NAME=mydatabase
    depends_on:
      mysql:
        condition: service_healthy
    
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: mydatabase
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5  
    volumes:
      - mysql-data:/var/lib/mysql  
  

volumes:
  mysql-data: